---
- name: Ensure software is installed and configured, does not require a venv
  hosts: localhost
  vars:
    ansible_user: "{{ lookup('env','USER') }}"
    ansible_connection: local
  roles:
  - name: managed_ansible_content