---
- hosts: localhost
  vars:
    ansible_user: "{{ lookup('env','USER') }}"
    ansible_connection: local
  roles:
  - name: korbad.project_management.managed_git_repo
    vars:
      managed_git_repo_dirname: korbad_secure_workstation
      git_url: https://github.com/Korbad/secure_workstation.git
      git_pull: true
  - name: korbad.project_management.managed_ansible_collection
    vars:
      git_url: https://github.com/Korbad/ansible-collection-korbad.workstation.git
      collection_namespace: korbad
      collection_name: workstation
      git_pull: true
  - name: korbad.secrets managed_ansible_collection
    vars:
      git_url: https://github.com/Korbad/ansible-collection-korbad.secrets.git
      collection_namespace: korbad
      collection_name: secrets
      git_pull: true
  - name: korbad.project_management.managed_ansible_collection
    vars:
      git_url: https://github.com/kewlfft/ansible-aur.git
      collection_namespace: kewlfft
      collection_name: aur