---
- hosts: localhost
  vars:
    ansible_user: "{{ lookup('env','USER') }}"
    ansible_connection: local
  roles:
  - name: korbad.workstation.discord
  - name: korbad.workstation.1password
  - name: korbad.workstation.chrome
  - name: korbad.workstation.korbad

  # ???? code oss settings file
  # - name: korbad.workstation.code_oss

  # plasma tweaks requires psutil in venv
  # - name: korbad.workstation.plasma_tweaks

  # - name: korbad.workstation.disable_power_saving
