---
- hosts: localhost
  vars:
    ansible_user: "{{ lookup('env','USER') }}"
    ansible_connection: local
  roles:
  - generic
  - secrets
  - management_onboarding
  - development
  - korbad.workstation.ssh_keygen_display_public_key
