---
- name: Ensure software is installed and configured, does not require a venv
  hosts: localhost
  vars:
    ansible_user: "{{ lookup('env','USER') }}"
    ansible_connection: local
  roles:
  - name: korbad.workstation.git_https_instead_of_ssh
  - name: korbad.workstation.sudoers_current_user
  - name: korbad.project_management.managed_vault_file