---
- hosts: localhost
  vars:
    ansible_user: "{{ lookup('env','USER') }}"
    ansible_connection: local
  roles:
  - name: korbad.workstation.discord
  - name: korbad.workstation.1password
  - name: korbad.workstation.chrome
