---
- name: Ensure vault password file exists for current user
  hosts: localhost
  vars:
    ansible_user: "{{ lookup('env','USER') }}"
    ansible_connection: local
  roles:
  - name: korbad.project_management.managed_vault_file